### ISSUE TITLE
Invalid date conversion!

### ISSUE THREAD

**Issue by sumanchapai** [opensource-nepal/go-nepali#15]
Run the following code

```go
package main

import (
	"fmt"

	"github.com/opensource-nepal/go-nepali/dateConverter"
)

type AD struct {
	year  int
	month int
	day   int
}

func main() {
	ads := []AD{
		{2024, 6, 13},
		{2024, 6, 14},
	}
	for _, ad := range ads {
		bs, err := dateConverter.EnglishToNepali(ad.year, ad.month, ad.day)
		if err != nil {
			panic(err)
		}
		fmt.Printf("%v-%v-%v-AD\n", ad.year, ad.month, ad.day)
		fmt.Printf("%v-%v-%v-BS\n", bs[0], bs[1], bs[2])
		fmt.Printf("\n\n")
	}
}
```

and you'll get as output

```
2024-6-13-AD
2081-2-31-BS


2024-6-14-AD
2081-3-1-BS
```

Note that conversion of 2024-6-13-AD is correct while the next day is not! 2024-6-14-AD should be 2081-2-32-BS!

<img width="870" alt="image" src="https://github.com/opensource-nepal/go-nepali/assets/26862106/df1abdae-93f5-48c4-b60c-465351f83aa9">

**Comment by aj3sh** [comment]
Hi @sumanchapai, thank you for reporting the bug! I've created a PR to address the current issue. However, we've encountered inconsistent date data on various Patros after the year 2081. We'll look into the matter promptly.

**Comment by sumanchapai** [comment]
Thanks. It's interesting to know that there's no consistency. If it helps, here's the data scraped from hamropatro for till: https://github.com/sumanchapai/patro/tree/main/data

**Comment by aj3sh** [comment]
I've noticed that Hamropatro has a total of 367 days in the year 2087, so I don't believe it has the correct data. I appreciate your help though.

**Comment by aj3sh** [comment]
PR has been merged and created a new release with the tag `v0.2.1`

**Comment by dantwoashim** [comment]
Hi, I was collecting public Nepali date regression cases for Project Parva’s conformance suite and added this as a historical regression fixture.

This issue is useful because it has a very clear boundary case:

* `2024-06-13 AD` → `2081-02-31 BS`
* `2024-06-14 AD` was reported as `2081-03-01 BS`, while the expected value was `2081-02-32 BS`

I also noticed the discussion here around inconsistent month data after 2081 and the later link to `node-nepali-datetime#82`, so I marked this as both a conversion-boundary regression case and part of the wider source-provenance/future-BS uncertainty problem.

No dependency or integration is required. Sharing in case it is useful for future regression/conformance tests:

https://github.com/dantwoashim/Project_Parva/blob/main/docs/benchmarks/NEPALI_DATE_CONFORMANCE_INDEX.md

I’ve kept it marked as a public regression case, not official calendar authority.
